apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app

spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      #take images from docker-hub - specifically example-voting-app
      ports:
        - containerPort: 80
          #we need port to be exposed